version: '3'
services:
  graphql-server:
    image: ${{ secrets.DOCKER_USERNAME }}/my-graphql-server:latest
    ports:
      - "80:4000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"

